<div class="page-title"><?php echo $this->headTitle()->getContainer()->getValue();?></div>
<?php if ($this->errorMessages) : ?>
    <div class="error-messages">
        <h4 class="error-messages-title">Please correct the following:</h4>
        <span class="error-messages-message"><?php echo $this->errorMessages; ?></span>
    </div>
<?php endif; ?>
<div class="forms" id="course-register">
    <?php echo $this->feedbackCourseForm; ?>
</div>